config/routes.rb
GardenMaster::Application.routes.draw do
  resources :plants

  root :to => "plants#index"

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  def when_to_plant= s
    case s
    when /(\d+)-(\d+) weeks after/
      self.adlf_min =  $1.to_i
      self.adlf_max =  $2.to_i
    when /(\d+) weeks after/
      self.adlf_min =  $1.to_i
      self.adlf_max =  $1.to_i
    when /(\d+)-(\d+) weeks before/
      self.adlf_min = -( $1.to_i )
      self.adlf_max = -( $2.to_i )
    when /(\d+) weeks before/
      self.adlf_min = -( $1.to_i )
      self.adlf_max = -( $1.to_i )
    when 'On ADLF'
      self.adlf_min = 0
      self.adlf_max = 0
    end
  end

  def rows_per_bed= s
    case s
    when /(\d+) alt/
      self[:rows_per_bed] = $1.to_i
      self.alternate_rows = true
    else
      self[:rows_per_bed] = s.to_i
      self.alternate_rows = false
    end
  end

  def feedings= s
    case s
    when /(\d+)-(\d+)/
      self.feedings_min = $1
      self.feedings_max = $2
    else
      self.feedings_min = s
      self.feedings_max = s
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  # GET /plants
  # GET /plants.xml
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plants }
    end
  end

  # GET /plants/1
  # GET /plants/1.xml
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/new
  # GET /plants/new.xml
  def new
    @plant = Plant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.xml
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to(@plant, :notice => 'Plant was successfully created.') }
        format.xml  { render :xml => @plant, :status => :created, :location => @plant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.xml
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to(@plant, :notice => 'Plant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.xml
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to(plants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GardenMaster</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :yield %><br />
    <%= f.text_field :yield %>
  </div>
  <div class="field">
    <%= f.label :yield_unit %><br />
    <%= f.text_field :yield_unit %>
  </div>
  <div class="field">
    <%= f.label :hardiness %><br />
    <%= f.text_field :hardiness %>
  </div>
  <div class="field">
    <%= f.label :adlf_min %><br />
    <%= f.text_field :adlf_min %>
  </div>
  <div class="field">
    <%= f.label :adlf_max %><br />
    <%= f.text_field :adlf_max %>
  </div>
  <div class="field">
    <%= f.label :seed %><br />
    <%= f.text_field :seed %>
  </div>
  <div class="field">
    <%= f.label :spacing %><br />
    <%= f.text_field :spacing %>
  </div>
  <div class="field">
    <%= f.label :rows_per_bed %><br />
    <%= f.text_field :rows_per_bed %>
  </div>
  <div class="field">
    <%= f.label :alternate_rows %><br />
    <%= f.check_box :alternate_rows %>
  </div>
  <div class="field">
    <%= f.label :depth %><br />
    <%= f.text_field :depth %>
  </div>
  <div class="field">
    <%= f.label :feedings_min %><br />
    <%= f.text_field :feedings_min %>
  </div>
  <div class="field">
    <%= f.label :feedings_max %><br />
    <%= f.text_field :feedings_max %>
  </div>
  <div class="field">
    <%= f.label :avg_height %><br />
    <%= f.text_field :avg_height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Plants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Count</th>
    <th>Yield</th>
    <th>Hardiness</th>
    <th>Adlf</th>
    <th>Seed</th>
    <th>Space</th>
    <th>Rows</th>
    <th>Depth</th>
    <th>Feedings</th>
    <th>Avg height</th>
    <th><%= link_to 'New', new_plant_path %></th>
    <th></th>
  </tr>

<% @plants.each do |plant| %>
  <tr>
    <td><%= link_to plant.name, plant %></td>
    <td><%= plant.count %></td>
    <td><%= plant.yield %> <%= plant.yield_unit %></td>
    <td><%= plant.hardiness %></td>
    <td><%= plant.adlf_min %>..<%= plant.adlf_max %></td>
    <td><%= plant.seed %></td>
    <td><%= plant.spacing %>"</td>
    <td><%= plant.rows_per_bed %><%= plant.alternate_rows ? ' alt' : '' %></td>
    <td><%= plant.depth %>"</td>
    <td><%= plant.feedings_min %>..<%= plant.feedings_max %></td>
    <td><%= plant.avg_height %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plant.name %>
</p>

<p>
  <b>Count:</b>
  <%= @plant.count %>
</p>

<p>
  <b>Yield:</b>
  <%= @plant.yield %>
</p>

<p>
  <b>Yield unit:</b>
  <%= @plant.yield_unit %>
</p>

<p>
  <b>Hardiness:</b>
  <%= @plant.hardiness %>
</p>

<p>
  <b>Adlf min:</b>
  <%= @plant.adlf_min %>
</p>

<p>
  <b>Adlf max:</b>
  <%= @plant.adlf_max %>
</p>

<p>
  <b>Seed:</b>
  <%= @plant.seed %>
</p>

<p>
  <b>Spacing:</b>
  <%= @plant.spacing %>
</p>

<p>
  <b>Rows per bed:</b>
  <%= @plant.rows_per_bed %>
</p>

<p>
  <b>Alternate rows:</b>
  <%= @plant.alternate_rows %>
</p>

<p>
  <b>Depth:</b>
  <%= @plant.depth %>
</p>

<p>
  <b>Feedings min:</b>
  <%= @plant.feedings_min %>
</p>

<p>
  <b>Feedings max:</b>
  <%= @plant.feedings_max %>
</p>

<p>
  <b>Avg height:</b>
  <%= @plant.avg_height %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>